export const PT_BR = {
  app: {
    title: 'Sistema de Gestão - Quórum de Élderes',
    subtitle: 'Ala Horizonte Azul',
  },
  nav: {
    dashboard: 'Painel',
    members: 'Membros',
    families: 'Famílias',
    ministering: 'Ministração',
    meetings: 'Reuniões',
    activities: 'Atividades',
    goals: 'Metas',
    reports: 'Relatórios',
    settings: 'Configurações',
  },
  auth: {
    login: 'Entrar',
    logout: 'Sair',
    email: 'guiverdoodt92@gmail.com',
    password: 'admin123',
    president: 'Presidente',
    firstCounselor: '1º Conselheiro',
    secondCounselor: '2º Conselheiro',
    selectRole: 'Selecione seu chamado',
    welcome: 'Bem-vindo',
  },
  dashboard: {
    title: 'Painel de Controle',
    overview: 'Visão Geral',
    totalMembers: 'Total de Membros',
    totalFamilies: 'Total de Famílias',
    activeCompanionships: 'Duplas Ativas',
    ministeringCompletion: 'Ministração Concluída',
    needsAttention: 'Precisam de Atenção',
    birthdays: 'Aniversários do Mês',
    newMembers: 'Novos Membros',
    lessActive: 'Menos Ativos',
    upcomingActivities: 'Próximas Atividades',
    recentGoals: 'Metas Recentes',
  },
  members: {
    title: 'Membros',
    addMember: 'Adicionar Membro',
    editMember: 'Editar Membro',
    deleteMember: 'Excluir Membro',
    searchMembers: 'Buscar membros...',
    fullName: 'Nome Completo',
    gender: 'Sexo',
    age: 'Idade',
    birthDate: 'Data de Nascimento',
    phone: 'Telefone',
    email: 'E-mail',
    address: 'Endereço',
    street: 'Rua',
    number: 'Número',
    neighborhood: 'Bairro',
    zipCode: 'CEP',
    family: 'Família',
    activityStatus: 'Status de Atividade',
    priesthood: 'Sacerdócio',
    priesthoodOffice: 'Ofício do Sacerdócio',
    templeRecommend: 'Recomendação do Templo',
    relationship: 'Parentesco',
    notes: 'Observações',
    specialNeeds: 'Necessidades Especiais',
    spiritualImpressions: 'Impressões Espirituais',
    male: 'Masculino',
    female: 'Feminino',
    active: 'Ativo',
    lessActive: 'Menos Ativo',
    inactive: 'Inativo',
    new: 'Novo',
    deacon: 'Diácono',
    teacher: 'Mestre',
    priest: 'Sacerdote',
    elder: 'Élder',
    highPriest: 'Sumo Sacerdote',
    none: 'Nenhum',
    father: 'Pai',
    mother: 'Mãe',
    son: 'Filho',
    daughter: 'Filha',
    spouse: 'Cônjuge',
    other: 'Outro',
  },
  families: {
    title: 'Famílias',
    addFamily: 'Adicionar Família',
    editFamily: 'Editar Família',
    deleteFamily: 'Excluir Família',
    searchFamilies: 'Buscar famílias...',
    familyName: 'Nome da Família',
    mainPhone: 'Telefone Principal',
    mainEmail: 'E-mail Principal',
    companionship: 'Dupla Ministrante',
    members: 'Membros',
    viewDetails: 'Ver Detalhes',
  },
  ministering: {
    title: 'Ministração',
    companionships: 'Duplas Ministrantes',
    visits: 'Visitas',
    addCompanionship: 'Adicionar Dupla',
    editCompanionship: 'Editar Dupla',
    deleteCompanionship: 'Excluir Dupla',
    companionshipName: 'Nome da Dupla',
    companion1: 'Companheiro 1',
    companion2: 'Companheiro 2',
    assignedFamilies: 'Famílias Atribuídas',
    active: 'Ativa',
    inactive: 'Inativa',
    recordVisit: 'Registrar Visita',
    visitDate: 'Data da Visita',
    contactType: 'Tipo de Contato',
    completed: 'Realizada',
    pending: 'Pendente',
    identifiedNeeds: 'Necessidades Identificadas',
    monthReference: 'Mês de Referência',
    inPerson: 'Presencial',
    phone: 'Telefone',
    message: 'Mensagem',
    virtual: 'Virtual',
    visitHistory: 'Histórico de Visitas',
    completionRate: 'Taxa de Conclusão',
    overdueVisits: 'Visitas Atrasadas',
  },
  meetings: {
    title: 'Reuniões',
    addMeeting: 'Adicionar Reunião',
    editMeeting: 'Editar Reunião',
    deleteMeeting: 'Excluir Reunião',
    meetingTitle: 'Título da Reunião',
    meetingType: 'Tipo de Reunião',
    date: 'Data',
    time: 'Horário',
    location: 'Local',
    participants: 'Participantes',
    agenda: 'Pauta',
    discussions: 'Discussões',
    decisions: 'Decisões',
    actionItems: 'Itens de Ação',
    presidency: 'Presidência',
    quorum: 'Quórum',
    council: 'Conselho',
    activity: 'Atividade',
    addAgendaItem: 'Adicionar Item da Pauta',
    addDecision: 'Adicionar Decisão',
    addActionItem: 'Adicionar Ação',
    assignedTo: 'Atribuído a',
    dueDate: 'Data de Vencimento',
    status: 'Status',
    meetingMinutes: 'Ata da Reunião',
  },
  activities: {
    title: 'Atividades',
    addActivity: 'Adicionar Atividade',
    editActivity: 'Editar Atividade',
    deleteActivity: 'Excluir Atividade',
    activityName: 'Nome da Atividade',
    activityType: 'Tipo de Atividade',
    date: 'Data',
    time: 'Horário',
    location: 'Local',
    description: 'Descrição',
    budget: 'Orçamento',
    plannedBudget: 'Orçamento Previsto',
    actualBudget: 'Orçamento Real',
    responsible: 'Responsável',
    participants: 'Participantes',
    totalParticipants: 'Total de Participantes',
    evaluation: 'Avaliação',
    feedback: 'Feedback',
    service: 'Serviço',
    social: 'Social',
    spiritual: 'Espiritual',
    sports: 'Esportiva',
    cultural: 'Cultural',
    planned: 'Planejada',
    ongoing: 'Em Andamento',
    completed: 'Concluída',
    cancelled: 'Cancelada',
    upcomingActivities: 'Próximas Atividades',
    pastActivities: 'Atividades Passadas',
  },
  goals: {
    title: 'Metas',
    addGoal: 'Adicionar Meta',
    editGoal: 'Editar Meta',
    deleteGoal: 'Excluir Meta',
    goalTitle: 'Título da Meta',
    goalType: 'Tipo de Meta',
    member: 'Membro',
    description: 'Descrição',
    startDate: 'Data de Início',
    targetDate: 'Data Alvo',
    status: 'Status',
    progress: 'Progresso',
    milestones: 'Marcos',
    obstacles: 'Obstáculos',
    supportNeeded: 'Apoio Necessário',
    individual: 'Individual',
    quorum: 'Quórum',
    priesthood: 'Sacerdócio',
    reactivation: 'Reativação',
    temple: 'Templo',
    missionary: 'Missionário',
    onTrack: 'No Prazo',
    atRisk: 'Em Risco',
    delayed: 'Atrasada',
    completed: 'Concluída',
    cancelled: 'Cancelada',
    activeGoals: 'Metas Ativas',
    completedGoals: 'Metas Concluídas',
    goalProgress: 'Progresso da Meta',
  },
  reports: {
    title: 'Relatórios',
    generateReport: 'Gerar Relatório',
    exportReport: 'Exportar Relatório',
    ministeringReport: 'Relatório de Ministração',
    attendanceReport: 'Relatório de Frequência',
    activityReport: 'Relatório de Atividades',
    goalReport: 'Relatório de Metas',
    geographicReport: 'Relatório Geográfico',
    customReport: 'Relatório Personalizado',
    selectReportType: 'Selecione o tipo de relatório',
    selectDateRange: 'Selecione o período',
    selectFilters: 'Selecione os filtros',
    monthlyReport: 'Relatório Mensal',
    quarterlyReport: 'Relatório Trimestral',
    annualReport: 'Relatório Anual',
  },
  geographic: {
    title: 'Visualização Geográfica',
    filterByNeighborhood: 'Filtrar por Bairro',
    filterByStreet: 'Filtrar por Rua',
    filterByZipCode: 'Filtrar por CEP',
    memberDistribution: 'Distribuição de Membros',
    neighborhoods: 'Bairros',
    selectNeighborhood: 'Selecione um bairro',
    membersInArea: 'Membros na Área',
    familiesInArea: 'Famílias na Área',
  },
  common: {
    save: 'Salvar',
    cancel: 'Cancelar',
    delete: 'Excluir',
    edit: 'Editar',
    add: 'Adicionar',
    search: 'Buscar',
    filter: 'Filtrar',
    export: 'Exportar',
    import: 'Importar',
    loading: 'Carregando...',
    noData: 'Nenhum dado disponível',
    confirm: 'Confirmar',
    yes: 'Sim',
    no: 'Não',
    viewDetails: 'Ver Detalhes',
    close: 'Fechar',
    back: 'Voltar',
    next: 'Próximo',
    previous: 'Anterior',
    selectAll: 'Selecionar Todos',
    deselectAll: 'Desselecionar Todos',
    actions: 'Ações',
    success: 'Sucesso',
    error: 'Erro',
    warning: 'Aviso',
    info: 'Informação',
  },
  errors: {
    generic: 'Ocorreu um erro. Tente novamente.',
    notFound: 'Não encontrado',
    unauthorized: 'Não autorizado',
    invalidData: 'Dados inválidos',
    networkError: 'Erro de conexão',
  },
};
